# User
userId : "<samplify userId>"  # e.g. userid : "kolart"
userEmail : "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory : "<full path to sample directory>"    # e.g. sampleDirectory "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleQCDirectory : "<full path to sample QC directory>"  # e.g. sampleDirectory "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
sampleId : <samplify sampleId>  # e.g sampleId : 123456

# CCS Bams
ccsBams : [ <comma delmited list of full paths to ccs bams> ]
# e.g. ccsBams : ["/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs1-2_downsampled.bam","/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs2-2_downsampled.bam"]

# VerifyBamID
verifyBamId_additionalParameters : <any additional parameters for verifyBamId>
# e.g. verifyBamId_additionalParameters : "--DisableSanityCheck"  ## note that this exact parameter is needed for testing
