##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"    # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleQCDirectory: "<full path to sample QC directory>"  # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
sampleId: <samplify sampleId>  # e.g sampleId: 123456

# Target
sequencingTarget: "<name of sequencing target>"   # e.g. sequencingTarget: "WHOLE_GENOME"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"    # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/pacbio/human_GRCh38_no_alt_analysis_set.fasta"

# Fingerprint Bed
fingerprintBed: "<full path to fingerprint bed>"    # e.g. fingerprintBed: "/net/nwgc/vol1/references/human/grc38/targets/fingerprint_grc38_aou.bed"

# HiFI Bams
hiFiBams:
  - "<full path to first hiFiBam>"
  - "<full path to second hiFiBam>"
  - "<repeat for more hiFiBams>"
# e.g.
#hiFiBams:
#  - "/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs1-2_downsampled.bam"
#  - "/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs2-2_downsampled.bam"

##########################################
### TOOLS
##########################################

# Map Hifi Bams
mapHiFiBams_numCPUs: <Number of CPUs to use for MapHiFiBams Process>   # e.g. mapHiFiBams_numCPUs: 10
mapHiFiBams_memory: "<Memory to use for MapHiFiBams Process>"          # e.g. mapHiFiBams_memory: "2G"

# Merge Mapped Bams
mergeMappedBams_numCPUs: <Number of CPUs to use for MergeMappedBams Process>   # e.g. mergeMappedBams_numCPUs: 20
mergeMappedBams_memory: "<Memory to use for MergeMappedBams Process>"          # e.g. mergeMappedBams_memory: "1G"

# Add NM Tags
addNMTags_numCPUs: <Number of CPUs to use for AddNMTags Process>   # e.g. addNMTags_numCPUs: 10
addNMTags_memory: "<Memory to use for AddNMTags Process>"          # e.g. addNMTags_memory: "2G"

# Samtools stats
samtoolsStats_numCPUs: <Number of CPUs to use for SamtoolsStats Process>   # e.g. samtoolsStats_numCPUs: 10
samtoolsStats_memory: "<Memory to use for SamtoolsStats Process>"          # e.g. samtoolsStats_memory: "2G"

# Picard Quality Metrics
picardQualityMetrics_memory: "<Memory to use for PicardQualityMetrics Process>"          # e.g. picardQualityMetrics_memory: "10G"

# Picard Coverage Metrics
picardCoverageMetrics_memory: "<Memory to use for PicardCoverageMetrics Process>"            # e.g. picardCoverageMetrics_memory: "20G"
# These two parameters appear to make the program run faster and consume memory within the limits of that specified above
picardCoverageMetrics_initialRAMPercentage: <percentage of memory to use initially in RAM>"  # e.g. picardCoverageMetrics_initialRAMPercentage: "90"
picardCoverageMetrics_maxRAMPercentage: <max percentage of memory in RAM>"  				 # e.g. picardCoverageMetrics_maxRAMPercentage: "95"

# NanoPlot
nanoPlot_numCPUs: <Number of CPUs to use for NanoPlot Process>   # e.g. nanoPlot_numCPUs: 10
nanoPlot_memory: "<Memory to use for NanoPlot Process>"          # e.g. nanoPlot_memory: "2G"

# Contamination Check
contaminationCheck_memory: "<Memory to use for ContaminationCheck Process>"      # e.g. contaminationCheck_memory: "10G"
verifyBamId_additionalParameters: "<Usually blank, needed for testing>"   # e.g. verifyBamId_additionalParameters : "--DisableSanityCheck"  ## note that this exact parameter is needed for testing

# Fingerprint
createFingerprintVcf_memory: "<Memory to use for CreateFingerprintVCF Process>"      # e.g. createFingerprintVcf_memory: "10G"
